### PR TITLE
Fix #55: added support for BASIC auth.

### LINKED ISSUE #55: Needs authentication
People can edit other people and add themselves.

### PR DESCRIPTION
**Pull request by dblock**
Set `SUP_USERNAME` to a username.
Set `SUP_PASSWORD_HASH` to

```ruby
require 'bcrypt'
BCrypt::Password.create('password')
```

### CODE REVIEW

**Comment by ilyakava** [comment]
Do I understand correctly that there's only 1 username and password? Is this so that only 1 person at an organization can access sup (or will it be shared within the organization)?

I ask b/c there are a few popular access points for members:
- opting out of sups by [checking a box](https://github.com/ilyakava/sup/blob/master/app/views/members/_edit_form.html.erb#L26) on the member page
- responding to [weekly surveys](https://github.com/ilyakava/sup/blob/master/app/views/meetings/edit.html.erb) of who attended your sup + leaving [comments](https://github.com/ilyakava/sup/blob/master/app/views/feedbacks/new.html.erb) afterwards

It seems like these 2 end points will be affected, or am I missing something?

**Comment by ilyakava** [comment]
If you agree with what I said in this issue: https://github.com/ilyakava/sup/issues/57#issuecomment-151535472

Then I am good to merge if we exclude some things that should be publicly accessible
- graph
- list of users
  - in the future won't have email addresses
- edit page for user profile
  - in the future won't have email address, or save on submission until a confirmation email link has been clicked
- weekly survey page + comment page
  - both of these people get to via link in email address, so we can think of a way to secure this too

I am taking as assumption that the names of people working at a company (and their work group graph) might as well be publicly visible, but their email addresses should not

Thoughts @dblock ?

**Comment by dblock** [comment]
The first line of order is to secure sup altogether to a group. Adding BASIC auth was the quickest - we'll share the password. However in the long run this needs to be a permission-based system with everything you describe. It's a lot more work. None of the things you are describing should be "publicly" available under this PR, the password is for the team to share and continue using sup as is.

**Comment by ilyakava** [comment]
kk sounds good to me :boom: 

So in an ideal future, would the following being excluded from this before filter (and therefore being publicly accessible) be ok @dblock?

- graph of users w/ names only
- list of users (w/ names + active/not active status only)
- edit page for user profile (w/ names, group memberships, and active/not active status only)
- weekly survey page + comment page (via link in email address, maybe w/ some sort of expiring token in the link)

**Comment by dblock** [comment]
I opened https://github.com/ilyakava/sup/issues/62, just edit it to describe what you want to happen?

**Comment by bhoggard** [comment]
Code uses `SUP_USER_NAME` not `SUP_USERNAME` so I will set the former env var on heroku.

**Comment by dblock** [comment]
@bhoggard that was a typo in README too, fixed in https://github.com/ilyakava/sup/commit/970a7cfb7a277c38f9458d2180a16e7ce642e011

**Pull request merged**
