### PR TITLE
hidding email

### PR DESCRIPTION
**Pull request by 4p00rv**
Fix for issue #57 . As was mentioned in #61 fix that email address is still visible in input box, so I have put up a fix for hiding the email address in the input box too. 
screenshot from 2015-11-09 14 58 26

### CODE REVIEW

**Comment by dblock** [comment]
Lets get #64 in and we'll talk about this one after.

**Comment by 4p00rv** [comment]
Any remarks on this fix? Also I think I can take up #62 may be next month.

**Comment by ilyakava** [comment]
Some things in here were already included in #66 like the email->name swap in the `index.html`.

But I am a little torn on what to do about the email addresses.
- On one hand if the website is open to the public, then we want to hide addresses.
- But on the other hand, after https://github.com/ilyakava/sup/pull/58 its likely that few people would chose the website to be public, and if it is private it provides an easy way to look up email addresses as well as team memberships of your colleagues.

All things considered, my understanding after #58 is that we don't need to hide email addresses anymore, @dblock can comment more since he is closer to the use of S'up than I am now

**Comment by dblock** [comment]
I think we can leave the email addresses alone at this point.

**Comment by 4p00rv** [comment]
I think we can opt to hide email addresses in case the website is open to public. A private website in itself would make email address not scrape-able.

**Pull request closed without merging**
